apiVersion: v1
kind: List
items:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: wt-ibm
      app.kubernetes.io/component: wt-ibm
      app.kubernetes.io/instance: wt-ibm
    name: wt-ibm
  spec:
    replicas: 3
    revisionHistoryLimit: 10
    selector:
      deploymentconfig: wt-ibm
    template:
      metadata:
        labels:
          deploymentconfig: wt-ibm
      spec:
        containers:
        - image: wt-ibm
          imagePullPolicy: Always
          name: wt-ibm
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - wt-ibm
        from:
          kind: ImageStreamTag
          name: wt-ibm:test
      type: ImageChange
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      app: wt-ibm
      app.kubernetes.io/component: wt-ibm
      app.kubernetes.io/instance: wt-ibm
    name: wt-ibm
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: wt-ibm
      app.kubernetes.io/component: wt-ibm
      app.kubernetes.io/instance: wt-ibm
    name: wt-ibm
  spec:
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: wt-ibm
      weight: 100
    wildcardPolicy: None
